[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fun-utils"
version = "0.1.0"
description = "Tiny fun utilities ğŸ‰"
authors = [{ name = "Samir Marin", email = "marin.samir@gmail.com" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = []